name: portzapp-postgres

services:
  # This is your local Postgres database instance
  # Connection URL: postgres://dev:dev@localhost:5400/portzapp
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: portzapp
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./.docker-container-volumes/postgres-db-data:/var/lib/postgresql/data
    ports:
      - '5400:5432' # Access the DB at port 5400

  # Use Adminer Evo to quickly view the database at localhost:8900
  adminer:
    image: ghcr.io/shyim/adminerevo:latest
    restart: always
    ports:
      - '8900:8080'

  mailpit:
    image: axllent/mailpit:latest
    restart: always
    environment:
      MP_UI_AUTH: ''
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: '1'
      MP_SMTP_AUTH_ALLOW_INSECURE: '1'
    volumes:
      - ./.docker-container-volumes/mailpit-data:/data
    ports:
      - '8025:8025' # Web UI at http://localhost:8025
      - '1025:1025' # SMTP server at localhost:1025
